### ISSUE TITLE
Víc kontrolovat config

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#10]
Můžeme např. kontrolovat, zda se všechna řešení objevují v seznamu `solutions=...`, zda jsou vyřešena všechna `TODO`, další věci?

**Comment by vvolhejn** [comment]
Užitečné by bylo i detekovat a varovat, že jsou přítomné key-value pairs, které se nikam nezapsaly.

**Comment by vvolhejn** [comment]
Druhá část vyřešená v #92 (detekce zbytečných hodnot).

**Comment by 5K1PY** [comment]
Kontrolování TODO vyřešeno ve ``v2``. Bonzování řešení je již v #79
