### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by JiriKalvoda** [kasiopea-org/pisek#101]
Ahoj!

Bylo by prosím možné písku udělit nějakou Copyleftovou licenci (ideálně GNU General Public License v 3)?

Snažím se řešit nějaké problémy s výběrko-použitím a momentálně mi  nelicencovanost písku znemožňuje uvažovat nad řešením obsahující využít nějaký kousek licencovaného kódu.

Moc díky.

**Comment by RichardHladik** [comment]
Ahoj, za mě ack, ačkoliv se nepovažuju za hlavního autora (@vvolhejn). Za mě asi taky mírná preference pro GPLv3, ale preferuji cokoliv příčetného před vedením svatých válek, jaká licence je nejlepší 😀

**Comment by jiribenes** [comment]
Ζa mě OK, touto zprávou umožňuji distribuci mého kódu v tomto projektu pod GPLv3 licencí.
Jen pozor, že v každém zdrojovém souboru bude potřeba mít obligátní GPLv3 hlavičku :)

**Comment by vvolhejn** [comment]
klíďo :)

**Comment by Mnaukal** [comment]
Za mě taky ok.

**Comment by JiriKalvoda** [comment]
Moc díky všem.
