### ISSUE TITLE
Podporovat další jazyky

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#11]
Momentálně umíme C++ a Python, chceme další jazyky? V Kasiopei myslím, že to není urgentní, protože jiné jazyky moc nepoužíváme, ale do budoucna možná?

**Comment by jiribenes** [comment]
> V Kasiopei myslím, že to není urgentní, protože jiné jazyky moc nepoužíváme, ale do budoucna možná?

Na domácí kolo se hodí podporovat jazyky jako Pascal, C# a Java, protože v nich máme vzorová řešení Ačka.

**Comment by jiribenes** [comment]
### Jak začít s touto issue:

Pro kompilaci používáme soubor [pisek/compile.py](https://github.com/kasiopea-org/pisek/blob/master/pisek/compile.py#L7), ve kterém je abstraktní třída `CompileRules`, která jen vezme cestu k podporovanému souboru a vrátí buď cestu ke spustitelnému (zkompilovanému) souboru nebo `None` značící chybu.

Pro ukázku stačí asi třídy `PythonCompileRules` a `CPPCompileRules` níže v tom samém souboru.
Je tedy třeba pro každý nový jazyk podobnou třídu přidat a naimplementovat.

Dále je potřeba přidat instanci nové třídy do globální proměnné `COMPILE_RULES` [zde](https://github.com/kasiopea-org/pisek/blob/master/pisek/compile.py#L66) spolu s podporovanými koncovkami. Nakonec by se změna měla otestovat.

---
V případě dotazů stačí jen napsat sem do issue :)

**Comment by vvolhejn** [comment]
Viz #52, nastává problém v případě, že člověk nemá kompilátor pro daný jazyk. Nerad bych spoléhal na jiné jazyky než C++ a Python, takže mi přijde, že tohle má poměrně malou užitečnost.
