### ISSUE TITLE
Kontrolovat unikátnost koncovek řešení se stejným názvem

### ISSUE THREAD

**Issue by jiribenes** [kasiopea-org/pisek#14]
Řešení by neměla mít stejný název, ale jinou koncovku, tedy může existovat jak `solve.py`, tak `solve.cpp`, ale v configu je jen `solve`.

Chceme tedy zkontrolovat, že je vždy jen jeden soubor, který sdílí svůj název s tím s configu!

**Comment by RichardHladik** [comment]
Mělo by být vyřešeno v 54917b6.
