### ISSUE TITLE
Nekonzistentní vypisování cest k souboru

### ISSUE THREAD

**Issue by trueMiskin** [kasiopea-org/pisek#150]
Písek vypisuje buď název nebo relativní cestu k souboru a když si nedáváte pozor, tak se mi několikrát stalo, že místo otevření vstupu, jsem si "vytvořil nový soubor" a divil jsem se, proč je ten vstup prázdný. "Nefunguje generátor nebo kam se poděl vstup?"

![image](https://github.com/kasiopea-org/pisek/assets/34354705/020b1585-4235-42d6-a9ce-7d2ff3a7a346)

**Comment by 5K1PY** [comment]
That's already solved in newest version of pisek.
