### ISSUE TITLE
Lepší zpráva v případě, že nesedí skóre řešení

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#16]
Momentálně se vypíše jen to, že řešení mělo dostat x bodů a dostalo y bodů.

Pokud řešení mělo získat víc, mohli bychom navíc vypsat, na jakém seedu je problém a (třešnička) kousek diffu ukazující, jak se liší očekávaný a skutečný výstup.

Tohle je podle mě docela důležité, protože bych čekal, že na tomhle budou testy selhávat při vývoji často.

**Comment by jiribenes** [comment]
V d425477 jsem přidal základní diffovátko pomocí `difflib`, která je v std. knihovně.
Asi by se ale ještě slušelo to doupravit a customizovat, je to celkem narychlo nabastlené.

**Comment by vvolhejn** [comment]
Tohle už myslím funguje dobře.
