### ISSUE TITLE
Progress bary

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#17]
Pro dlouho běžící řešení by bylo hezké mít představu, jak dlouho tak asi poběží.

Představuju si to tak, že jakmile doběhne vzorové řešení na jednom seedu, dá nám to odhad, jak velký má být výstup. Pak se můžeme koukat, kolik výstupu už běžící řešení vypsalo a podle toho odhadovat, kolik ještě zbývá -- nejsnažší bude použít `tqdm`

**Comment by RichardHladik** [comment]
Tohle je IMO z principu nemožné udělat dobře. Řekl bych, že u většiny úloh stejně načteš celý vstup, pár vteřin chroustáš a pak za zlomek vteřiny vyplivneš celý výsledek.

**Comment by IAmWave** [comment]
Myšleno pro Kasiopeu, kde jedno spuštění programu znamená vyřešení několika testů - tam je rozumné očekávat, že se vypisuje průběžně

**Comment by RichardHladik** [comment]
Pravda, na to jsem zapomněl… Tam to dává větší smysl.

**Comment by vvolhejn** [comment]
Částečně vyřešené - máme progress bary, které ukazují, na kolika seedech už program doběhl.

**Comment by vvolhejn** [comment]
Prohlašuji za vyřešené.
