### ISSUE TITLE
Spouštění generátoru

### ISSUE THREAD

**Issue by IAmWave** [kasiopea-org/pisek#2]
- [x] zkontrolovat, že `gen.*` existuje
- [x] zkompilovat generátor
- [x] umět vygenerovat vstup
- [x] ověřit determinističnost (pro jeden seed pořád stejné výstupy)
- [ ] zkontrolovat, že bere hex seed (jak?)
- [x] umět vygenerovat testovací sady pro potřebu kontrolování řešení

**Comment by jiribenes** [comment]
Nakonec hledáme generátor dle konfiguráku.
