### ISSUE TITLE
Vypsat stderr v případě, že program spadne

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#20]
Momentálně když program selže (např. když generátor na nějakém assertu), nedozvíme se, co přesně se stalo. Řešením by bylo uložit si někam stderr a ten pak vypsat.

**Comment by RichardHladik** [comment]
Nebo se stderr prostě nemusí přesměrovávat. Přijde mi, že u generátoru chceme stderr vypisovat vždycky, u judge pokud vrátí nenulovou návratovou hodnotu, a u řešení jak kdy (když mám řešení, které má na větších testech vyžrat paměť, nechci, aby mi to plevelilo výstup, ale zase můžu mít legitimní řešení, které chci zdebugovat).
Nejjednodušší je asi přidat nějaký switch, --[no-]capture-stderr?

**Comment by vvolhejn** [comment]
Vyřešeno pro generátory a judge, poslední část v a29c5a1. Nakonec prostě vypisujeme stderr vždy, nenapadají mě příklady, kde to nechceme. Pro `OfflineGenerator` (kde předpokládáme, že může běžet dlouho), to dokonce vypisuje stderr ještě za běhu.

Zbývá vymyslet, jak a jestli to dělat pro řešení. Živý stderr je nějak složitý s timeoutem, předávat ho by mělo jít celkem v pohodě.
