### ISSUE TITLE
Timeout řešení by neměl znamenat chybu

### ISSUE THREAD

**Issue by IAmWave** [kasiopea-org/pisek#21]
Momentálně pokud řešení běží moc dlouho, řekneme, že nastala chyba, přitom to může být očekávaný výsledek v případě řešení, které má získat jen 4 body a na těžkou variantu má být pomalé.

Tohle je dost časté, takže bychom to měli rychle vyřešit.

**Comment by jiribenes** [comment]
Na určení proč něco selhalo by šel použít nějaký enum, který by vracel run, vytvořený vlastní analýzou returncode.
Tuším že když to hodí timeout, tak ten proces zabije nějakým signálem a vrátí returncode jako -číslo signálu

**Comment by IAmWave** [comment]
Ono to dokonce hodí TimeoutExpired exception, takže není problém to
detekovat

**Comment by IAmWave** [comment]
Vyřešeno [zde](https://github.com/kasiopea-org/pisek/commit/dcc5e238c5bb623d60963d16159ba79a353aa9c2)
