### ISSUE TITLE
Kontrolovat, že řešení projde/neprojde nezávisle na seedu

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#24]
Pokud má řešení dostat 4 body, mělo by selhat na těžké obtížnosti, a to ať už je seed jakýkoliv. Momentálně nám stačí, pokud selže na nějakém seedu.

**Comment by JanKaifer** [comment]
+1. Teď se mi stalo tohle:

`Řešení solve_hungry_4b získá 4b ... |·····|··W| ok`.

A kdybych si toho nevšiml, tak šlo do domácího kola něco co šlo hladově obejít.

**Comment by 5K1PY** [comment]
Opraveno ve ``v2``.
