### ISSUE TITLE
Podpora pro skupiny testů

### ISSUE THREAD

**Issue by RichardHladik** [kasiopea-org/pisek#29]
CMSko a jiné systémy podporují skupiny testů – co jeden subtask, to jedna skupina skládající se z několika testů, pro získání bodů za subtask je potřeba vyřešit všechny testy ve skupině.

Tohle budou úlohy na výběrku mít, tak by bylo dobré, kdyby to uměl Písek otestovat – jinak nebudou počty bodů za řešení dávat smysl.

**Comment by vvolhejn** [comment]
Tohle je (už poměrně dlouho) hotové.
