### ISSUE TITLE
Nice-to-have výběrkové hooky

### ISSUE THREAD

**Issue by RichardHladik** [kasiopea-org/pisek#31]
Třeba:
- při generování testovacích dat kontrola, že máme pullnuto
- subcommand na zazipování testovacích dat k nahrání do CMSka
- libovolná automatizace nahrávání do CMSka
- …

**Comment by IAmWave** [comment]
Předtím jsem chtěl do Písku dát i třeba generování zadání z Markdownu do HTML (pro Kasiopeu), ale ty jsi říkal, že už to je jiný problém - tady mi to přijde trochu podobné. Resp. úplně nevím, jak to zakomponovat. Teoreticky se tomu ale nebráním

**Comment by RichardHladik** [comment]
> Předtím jsem chtěl do Písku dát i třeba generování zadání z Markdownu
> do HTML (pro Kasiopeu), ale ty jsi říkal, že už to je jiný problém -
> tady mi to přijde trochu podobné. Resp. úplně nevím, jak to
> zakomponovat. Teoreticky se tomu ale nebráním

Souhlasím. Přijde mi, že nejlepší by byla podpora pro rozšíření, která
by si mohla registrovat vlastní subcommandy, popř. hooky do již
existujících commandů. Ale nechal bych to teď otevřené, nemám to úplně
domyšlené a máme víc věcí, co hoří víc.

**Comment by 5K1PY** [comment]
Viz #113
