### ISSUE TITLE
Git hooky na CI

### ISSUE THREAD

**Issue by RichardHladik** [kasiopea-org/pisek#32]
Při pohledu do historie by se vyplatilo přidat git hooky, které zakážou commitovat/pushovat, dokud nebude procházet type check a formátování.

**Comment by IAmWave** [comment]
oops

**Comment by RichardHladik** [comment]
Myslím, že jsme v tom oba tak nastejno 😄

**Comment by IAmWave** [comment]
Vyřešeno v #33

**Comment by RichardHladik** [comment]
Přijde mi, že teď to zase s těmi unit testy trvá moc dlouho. IMHO tolik nevadí, když se na to, že failí unit testy, přijde až po pushi – stejně se občas testy prostě rozbijou, když budeme přidávat novou funkcionalitu po částech. Jsem pro to unit testy ze skriptu vyřadit a nechat je jen v CI.
