### ISSUE TITLE
Použít časový limit z configu

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#37]
Do configu se dá napsat časový limit v tomto formátu:

```
[limits]
# Time limit (seconds) for the model solution (first listed)
solve_time_limit=2
# Time limit (seconds) for other solutions
sec_solve_time_limit=2
```

Měli bychom tyto limity respektovat.

Podobně jdou specifikovat i jiné limity, viz specifikace formátu (převzato z KSP, ale teď nevím, kde to najít...)

**Comment by 5K1PY** [comment]
Opraveno ve ``v2``.
