### ISSUE TITLE
Podpora pro judge

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#4]
Momentálně umíme řešení porovnávat jen pomocí diffu, ale do budoucna by se hodila i podpora pro judge programy, které dostanou vstup, vzorový výstup a skutečný výstup, a rozhodnou, zda je skutečný výstup správně.

U judge bychom se pak chtěli ještě ujistit, že správně ignoruje trailing whitespace a nerozlišuje mezi `\n` a `\r\n` (oops)

Také bude potřeba kontrolovat třeba i to, že vzorové řešení dostane plný počet bodů.

**Comment by IAmWave** [comment]
Požadavky na judge z README úlohy:

V úlohách s jednoznačným výstupem nám stačí porovnat řešení účastníka s naším
řešením. Pokud je ale výstup nejednoznačný, je potřeba tzv. judge -- program,
který zkontroluje, zda je odevzdané řešení správné.

- [ ] ak sa nepodarí otvoriť `TEST_INPUT` alebo `TEST_OUTPUT` skončí s chybovým kódom 2
- [ ] príjma windowsové aj linuxové konce riadkov
- [ ] príjma všetky neceločíselné výsledky s odchylkou epsilon

**Comment by RichardHladik** [comment]
Základní podpora pro judge je, chybí ty pokročilé věci, jako kontrolování, že judge je invariantní vůči trailing whitespace, windowsovým koncům řádků, odchylce atd.

Přemýšlím, jak tyhle věci testovat systematicky. Na tom příkladu s epsilon je vidět, že to obecně ani moc nejde – nemůžeme po Písku čekat, že bude rozumět výstupu a bude umět pertubovat čísla. Whitespace je jiná věc, ale zase u nějakých stringových úloh může mít whitespace význam.

**Comment by jiribenes** [comment]
Možná by na tohle šel použít property testing (alá QuickCheck), pro Python existuje knihovna [Hypothesis](https://hypothesis.readthedocs.io/en/latest/#).
Mohli bychom vždy vzít nějaký vstup, o kterém víme, že platí a udělat `f(vstup)` a alespoň kontrolovat, že pokud `f` mění jen trailing space/konce řádků, tak by judge měl pro `f(vstup)` vypsat to samé jako pro `vstup`. :)

Hodně nerealistický nápad do budoucna: Kdybychom měli něco jako gramatiku vstupu a výstupu, tak bychom mohli úplně generovat náhodné validní zadání a podívat se jestli vygeneruje validní výstup.

**Comment by IAmWave** [comment]
Přijde mi rozumné předpokládat by default, že na whitespace nezáleží: nevím, kdy jsem naposledy viděl úlohu, kdy by to tak nebylo. Navíc ty úlohy děláme my, takže vždycky můžem tu úlohu udělat tak, aby na whitespace opravdu nezáleželo.

**Comment by RichardHladik** [comment]
Neprogramovat něco, dokud to nepotřebujem, zní rozumně, a souhlasím, že jsem se dlouho nepotkal s úlohou, která by byla whitespace-sensitive.

Můj problém s tímhle asi je, že mi to přijde moc pomalé, protože abychom si byli jistí, je asi potřeba pustit tenhle test na všechny testcasy (viz úlohy stylu "if (těžký vstup) načti_výstup_v_mírně_odlišném_formátu") a na několik pokusů o zwhitespacování. Ale nevidím, jak to udělat líp a souhlasím, že tohle je věc, kterou chceme kontrolovat.

Souhlasím s Vaškem, že psaní gramatiky je moc hardcore. Navíc psát (nejspíš ani ne bezkontextovou) gramatiku na něco jako "na vstupu dostanete graf seznamem hran, je zaručeno, že je souvislý", bych asi nechtěl 😀

**Comment by jiribenes** [comment]
Souhlasím, že je psaní gramatiky moc hardcore, proto je to jako "Hodně nerealistický nápad do budoucna" :D

Whitespaceování by IMO mohlo být klidně až v pokročilých testech a tudíž by nemuselo běžet vždy, ale jen když uživatel dá nějakou vlajku `-all` při finálním testování.

**Comment by vvolhejn** [comment]
Základní podpora přidaná v #45

**Comment by vvolhejn** [comment]
Tohle už jsme v Kasiopeji použili, a funguje.
