### ISSUE TITLE
Timeout pomocí subprocess.run může leakovat procesy

### ISSUE THREAD

**Issue by RichardHladik** [kasiopea-org/pisek#41]
Teď jsem při debugování jiného projektu zjistil, že subprocess.run s parametrem timeout není spolehlivý a někdy zůstane proces běžet na pozadí. Bylo by dobré otestovat, jestli se to děje i v Písku a případně co s tím dělat.

**Comment by 5K1PY** [comment]
Ve ``v2`` používáme ``minibox``, který tímhle netrpí.
