### ISSUE TITLE
Barevný výstup

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#42]
Mít barevný "syntax highlighting" by pomohlo čitelnosti výstupu; třeba už jen červeně zvýrazňovat chyby by bylo dobré.

**Comment by vvolhejn** [comment]
Částečně hotovo: citování výstupu jiných programů je teď zvýrazněné žlutě.

**Comment by 5K1PY** [comment]
Opraveno ve ``v2``. Chyby se nyní zobrazují červeně a výstupy programů žlutě.
