### ISSUE TITLE
Kompatibilita s Windows

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#43]
Momentálně nevíme, jestli Písek funguje na Windows. To bychom přitom chtěli, abychom měli kompatibilitu s větším počtem organizátorů, zvláště pak začátečníků.

**Comment by jiribenes** [comment]
Tohle by už mělo řešit CI na Windows se self-testy, ne?

**Comment by IAmWave** [comment]
Pravda, to mě nenapadlo. Ale asi bych stejně rád ověřil, jestli to opravdu spustitelné je, přece jen self-testy nejsou pořád úplně stoprocentní záruka.

**Comment by JiriKalvoda** [comment]
Písek chodí pod WSL, přímo na Windowsech to asi nikdo moc netestoval a je to momentálně striktně nedoporučovaný způsob použití.
