### ISSUE TITLE
Používat build system (Make/ninja)

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#46]
Jirka to už nakousl v #19, ale začíná se mi zdát, že je to podstatnější, než jsem původně myslel - issue #19 mluví jen o skrytých závislostech, které jsme dosud měli jakž takž pod kontrolou.

Velké zlepšení pro Písek by bylo automaticky detekovat, že není potřeba vstupy znovu generovat, protože už jsou vygenerované a generátor se nezměnil - tím by se ušetřilo hodně času. To je ale přesně to, co dělá build system (třeba Make). Abychom se vyhnuli reinventing the wheel a současně vyřešili #19, mohli bychom jen vygenerovat soubor pro nějaký buildsystem a nechat ho udělat dependency management.

Zběžným pohledem se mi líbí [ninja](https://ninja-build.org/manual.html):
- modernější/mocnější než Make [citation needed]
- dostupný jako pythoní package - nekomplikuje instalaci Písku
- mělo by s ním jít [vypisovat věci za běhu](https://ninja-build.org/manual.html#_the_literal_console_literal_pool)

Každopádně by to ale zabralo nějakou práci. Myslíte, že to stojí za to? @jiribenes @RichardHladik

**Comment by jiribenes** [comment]
Ahoj,

souhlasím s tím, že velká část toho, co dělá Písek je vlastně práce jakéhosi build systému.
Ninja je celkem dobrý systém (byť možná trochu low-level, ale to je naštěstí práce pro nás, nikoliv pro uživatele).

Zároveň pak bude jednodušší přidat další jazyky v #11, protože to bude jen nějaké ninja pravidlo.
S tím bychom pak mohli podporovat i složitější buildovací procesy jako mají Go a Rust. 

Za mě tedy +1 :heavy_plus_sign:

**Comment by RichardHladik** [comment]
Ahoj,

nepovažuju se moc za aktivního vývojáře, ale mám jeden bod do diskuze:

Pokud vím, tak jeden z hlavních důvodů, proč jsme se rozhodli vynalézt si kolo, bylo aby ho pak mohl používat třeba i nejmenovaný matematik na Windows (🙃) Nevím, jaký je stav teď, ale přidání build systému se zákonitě rovná přidání závislosti.

Jinak mi přijde, že asi proč ne a že to ve výsledku může vyjít dost hezky a nějaké věci to usnadnit. Ale říkám to jako pozorovatel, ruku k dílu bych spíš nepřipojil.

**Comment by 5K1PY** [comment]
Nyní používáme vlastní build systém s Joby popsaný v ``docs/jobs.md``.
