### ISSUE TITLE
Problémy s CRLF konci řádků řešení v Pythonu

### ISSUE THREAD

**Issue by Mnaukal** [kasiopea-org/pisek#48]
Když má řešení napsané v Pythonu windowsovské konce řádků, tak si písek neporadí s jeho kompilací a spadne s chybou `FileNotFoundError` (není mi jasné, proč padá zrovna s touhle chybou, protože ten soubor to vytvoří). Dost možná je problém s shebangem, který má navíc na konci "\r".

Spuštěno pomocí WSL2:
```
ERROR: Řešení solve_test získá 10b
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mnaukal/.local/lib/python3.6/site-packages/pisek/tests/kasiopea_test_suite.py", line 223, in runTest
    self.test_passes_sample()
  File "/home/mnaukal/.local/lib/python3.6/site-packages/pisek/tests/kasiopea_test_suite.py", line 163, in test_passes_sample
    self.solution, sample_in, sample_out, self.run_config
  File "/home/mnaukal/.local/lib/python3.6/site-packages/pisek/judge.py", line 98, in evaluate
    return evaluate_offline(white_diff, solution, input_file, run_config)
  File "/home/mnaukal/.local/lib/python3.6/site-packages/pisek/judge.py", line 64, in evaluate_offline
    res, output_file = solution.run_on_file(input_file, **run_config)
  File "/home/mnaukal/.local/lib/python3.6/site-packages/pisek/solution.py", line 22, in run_on_file
    res = program.run(self.executable, input_file, output_file, timeout)
  File "/home/mnaukal/.local/lib/python3.6/site-packages/pisek/program.py", line 36, in run
    timeout=timeout,
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Michal/Seminare/kasiopea/2020-2021/domaci_kolo/ulohy/A/build/solve_test': '/mnt/c/Michal/Seminare/kasiopea/2020-2021/domaci_kolo/ulohy/A/build/solve_test'
```

**Comment by jiribenes** [comment]
Hmm, to fakt vypadá, že Python daný soubor nenašel. :/
Má ten soubor dobré pravomoci? AFAICT by měl být aspoň čitelný a spustitelný.

**Comment by Mnaukal** [comment]
WSL ukazuje, že práva má, ale je to uložené na Windows filesystému, takže kdo ví :D

Nicméně když se konce řádků změní na LF, tak to funguje krásně, takže to musí být něco uvnitř toho souboru.

**Comment by jiribenes** [comment]
Zkus vytvořit následující soubor s _Windowsovými_ konci řádků, dát mu `chmod +x` a zapnout ho přes WSL2. Funguje?
``` 
#!/usr/bin/env python3

print("hello world")
```

**Comment by Mnaukal** [comment]
To si přesně stěžuje na shebang:
```
mnaukal@TopZenBook:/mnt/c/Michal/Seminare/kasiopea/2020-2021/domaci_kolo/ulohy/A$ ./hello.py 
/usr/bin/env: ‘python3\r’: No such file or directory
```

**Comment by jiribenes** [comment]
Uff, tak to pak moc nevím co s tím. :D
Fakt jsem doufal, že `/usr/bin/env` je portable.

Znamená to, že na Windowsech _nesmí_ být `env`-ovitý shebang?
Napadá tě co s tím?

**Comment by Mnaukal** [comment]
Možná, že rozumné řešení tohohle je prostě v kontrole shebangu zkontrolovat, jestli končí na "\r" a když jo, tak uživateli vynadat ať opraví konce řádků, protože stejně asi nechceme, aby řešení mělo windowsové konce řádků, když ho pak spouštíme na Gimlim.

**Comment by jiribenes** [comment]
OK. Chceš si to rovnou naimplementovat? :)

Byla by to drobná změna tady: https://github.com/kasiopea-org/pisek/blob/13f0f8f182d154d40cee0f7d7c71a456adc09f23/pisek/compile.py#L46-L58

a k tomu nějaký self-test, který kontroluje, že tohle něco dělá v
https://github.com/kasiopea-org/pisek/blob/13f0f8f182d154d40cee0f7d7c71a456adc09f23/pisek/self_tests/test_kasiopea.py
