### ISSUE TITLE
Cachování výsledků / pouštění podčástí tesů.

### ISSUE THREAD

**Issue by JanKaifer** [kasiopea-org/pisek#51]
Teď jsem zkoušel ladit úlohu pískem a je to super <3.

Asi dělám něco špatně :), jen jsem se chtěl zeptat jak řešíte následující problém:

Pár chyb se projevovalo až v pozdějších testech a byla otrava vždy čekat 4 minuty než se otestuje generátor, který jsem neměnil. Přišlo by mi fajn buď rozdělit běh písku na části  (jednotlivé testy očíslovat) a pak vždy být schopen pustit jen jeden konkrétní test, nebo přidat magii, třeba s hashováním, která nebude testovat soubory, které se nezměnili.

Dík

**Comment by jiribenes** [comment]
Poznámka: Tohle by IMO ideálně vyřešila issue https://github.com/kasiopea-org/pisek/issues/46.

**Comment by JanKaifer** [comment]
Hrál jsem si s píškem trochu déle a "pouštění podtestů" nevypadá moc proveditelně a cachování je duplicitní s #46 .

Zavírám issue jako duplikát #46.
