### ISSUE TITLE
Kontrolovat existenci překladače/interpreteru

### ISSUE THREAD

**Issue by jiribenes** [kasiopea-org/pisek#52]
S přidáním jazyků jejichž překladače/interpretery nemají všichni (jako C#, Haskell, Pascal atd.) bychom měli vyřešit situaci "co když nemáme všechny nutné programy".

Navrhuji před kompilací zkontrolovat které nástroje uživatel zrovna má (všechny nástroje mají AFAIK něco jako `gcc --version`) a vynechat kontrolu řešení, které neumíme přeložit.

Tohle nám může ale vybuchnout jinak -- co když je nějaké takové řešení primární?

**Comment by vvolhejn** [comment]
Obecně myslím že nechceme spoléhat na řešení napsaných v jazycích, o kterých nechceme předpokládat, že je každý má (tj. cokoliv kromě C++ a Pythonu). Každý by měl být schopný zkontrolovat správnost úlohy na svém počítači bez instalace dalších kompilátorů. Tím pádem by to primární řešení být nemělo. Samozřejmě, pokud to je už někde v historii, co naplat. V takovém případě bych při nepřítomnosti kompilátoru prostě vyhodil chybu, protože s tím nic neuděláme.

Use case, který mi dává smysl, je kontrola řešení, které pak dáváme jako vzorové u úloh, kde chceme mít hodně jazyků. Kvůli tomu by se tohle hodilo.
