### ISSUE TITLE
Chybová hláška při testování řešení na 4 body

### ISSUE THREAD

**Issue by minarjos** [kasiopea-org/pisek#53]
Při testování lehkého řešení (řešení se suffixem _4b), které nefunguje a selže na lehkém vstupu, Písek nejdříve správně nahlásí chybu a napíše, že řešení získává 0 bodů, ale mělo by získat 4. Potom však vypíše diff na těžkém vstupu (nebo to aspoň tvrdí), což není moc užitečné, protože nás pro toto řešení zajímají jenom lehké vstupy.

**Comment by vvolhejn** [comment]
Vyřešeno v 233f949
