### ISSUE TITLE
Bug: JudgeHandlesWhitespace nefunguje na Windows

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#54]
Problém, co našla Kristýna N. Písek při spuštění na Windows spadne na testu JudgeHandlesWhitespace a zahlásí, že judge selhal s chybovým kódem 3221225595.

Možná problém s upravováním konců řádků z `\n` na `\r\n` v případě, že původní už jsou `\r\n`?

**Comment by 5K1PY** [comment]
Ve ``v2`` už není relevantní.
