### ISSUE TITLE
Interaktivní úlohy?

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#60]
V CMS existují interaktivní úlohy, kde si řešení účastníka nějak povídá s judgem. Někdy se to řeší linuxovými pipy, ale na výběrku jsme používali i jednodušší variantu - zkompilujeme řešení společně. Jak došlo Ríšovi, v tomto případě by mohlo být docela jednoduché interaktivní úlohy zprovoznit, stačilo by někam strčit možnost upravit argumenty pro kompilaci řešení.

**Comment by RichardHladik** [comment]
Jako lowprio by mi přišlo fajn mít nějaký hack, jak to doopravdy dělat s oddělenými procesy a rourami. Buď přímo v Písku (`subprocess` umí vytvářet a popropojovávat roury, ne?), to je ale asi velký oser. Nebo nějaký C/C++ bastl, který bude oifdefovaný a bude umožňovat, aby se v Písku vše testovalo slinkováním (tj. slinkuju `reseni.cpp`, `grader.cpp`, `bastl.h`), ale naostro do CMSka by to umělo ten dvouprocesový model.

Protože dlouhodobě slinkování fakt **je** bad practice a hazard s tím, že se to účastníci nepokusí přečůrat (a zapomenout se a napsat grader, který dovolí účastníkovi napsat "JO, 100 BODŮ" a skončit, je snadné).

Akorát zatím nevím, jak to udělat jednoduše. Proto lowprio, nemáme nekonečně času.

**Comment by vvolhejn** [comment]
Upřímně, nepřijde mi to jako takový hazard. Jak jsme řešili na callu, můžeme udělat to, že slinkovaný program vypíše na začátku `$TAJNY_STRING` a grader zkontroluje, že tam tajný string opravdu je. A kdybychom se báli o to, že si to někdo přečte z paměti (a myslím, že počet účastníků, co by to dokázalo, je 0 až 1), můžeme ho vygenerovat dynamicky nějakým hashováním.

Mimochodem, tenhle issue souvisí i s #30.

**Comment by RichardHladik** [comment]
Asi důvod, proč mi to přijde o něco větší hazard (neříkám, že výrazně a oprávněně), je, že se na to dívám z dlouhodobějšího hlediska a ptám se "může se do 5 let objevit účastník, co se to bude snažit rozbít?" "můžeme do 5 let u nějaké úlohy zapomenout best practices a udělat nezabezpečený grader? nebo nepročítat podezřelá řešení, takže potenciálně někdo, kdo to rozbije, může uspět?"

To hashování se mi líbí. A je to možná dobrý kompromis, i když security by obscurity. Za mě asi dostatečné, pokud se nám podaří zajistit, že orgové budou v budoucnu vycházet ze správného templatu. (Ale to asi půjde, když budou na očích a nikoho nenapadne místo templatu radši hledat, jak na to, v nějaké obskurní úloze z 201x.)

**Comment by 5K1PY** [comment]
Viz issue #111
