### ISSUE TITLE
Nějak invalidovat cache, když generátor nedoběhne

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#65]
Hlavně pro `OfflineGenerator` se může stát, že nedoběhne, ale část souborů vytvoří. Pak si cache myslí, že je vše ok, i když není.

Vygenerované vstupy možná nechceme mazat kvůli debugování. Možná nejjednodušší řešení by bylo smazat zkompilovanou binárku generátoru.

**Comment by vvolhejn** [comment]
Je to problém i pro Kasiopeu, měním labely.

**Comment by 5K1PY** [comment]
Opraveno ve ``v2``. Nyní celý ``Job`` failne a při příštím spuštění se tedy musí spustit znovu.
