### ISSUE TITLE
Přepínač pro vývojový mód

### ISSUE THREAD

**Issue by RichardHladik** [kasiopea-org/pisek#66]
AFAIK workflow pro případ, kdy mi padá vzorové řešení, je pustit `pisek`, zjistit, že tam mám vykřičníček, a začít lovit, který test spadl. Bylo by fajn, aby `pisek -v` (nebo s jiným přepínačem) vypsal i test, na kterém to spadlo, a co se přesně stalo. V tom případě taky dává smysl invalidovat vždycky cache, aby nenanstal problém RE→WA, co jsem popsal v #64.

**Comment by RichardHladik** [comment]
Stejně tak přepínač `--ano-vim-že-to-spadne-ale-chci-pustit-i-všechny-ostatní-testy-prosím`

**Comment by vvolhejn** [comment]
Hm, myslím, že to není otázka přepínače, spíš něco, co chceme dělat vždycky. Pokud si správně pamatuju, chybové hlášky pro ostatní řešení už jsou celkem rozumné, tak jde asi primárně o to, spravit to pro vzorové řešení (kde není jiné řešení ke srovnání)

**Comment by RichardHladik** [comment]
Testoval jsem zabugovane vzorove reseni a potreboval jsem vedet, se kterymi ostatnimi resenimi se shoduje. Takhle to spadlo na prvnim spatnem a musel jsem je prohazovat v configu.

**Comment by vvolhejn** [comment]
Ukázalo se, že tenhle přepínač už jsme to měli, ale bylo to schované pod `pisek test all`. Předělal jsem to na `pisek --full`. To s RE výstupy ještě vyřešené není.

**Comment by 5K1PY** [comment]
Chyby teď vypisují i jméno Jobu, které obsahuje i název vstupu u spouštění programu / název výstupu u judgování.
