### ISSUE TITLE
Kontrolovat velikosti vstupů a výstupů

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#7]
Vstupy a výstupy by měly mít max desítky MB kvůli uploadování. Na finále to může být víc, když jsme lokálně (ale je práce navíc mezi tím rozlišovat)

**Comment by jiribenes** [comment]
Tohle by nemělo být až tak těžké, nějaké základní checkování jak je soubor velký už děláme v `GeneratorWorks::generate_any` ([zde](https://github.com/kasiopea-org/pisek/blob/1f0a9fa0464d93bc232f6cb8ce19bb760a5d5899/pisek/tests/kasiopea_test_suite.py#L60)), konkrétně můžeme zavolat `os.path.getsize` na výsledný input a output a zkontrolovat, jestli je daná velikost v mezích.

**Comment by 5K1PY** [comment]
Opraveno ve ``v2``. Nyní lze v configu nastavit klíče: ``input_max_size`` a ``output_max_size``, které vstupy a výstupy nesmí velikostí překročit.
