### ISSUE TITLE
Upozornit, když není Písek na nejnovější verzi

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#71]
Uživatelé instalující pomocí `pip3 install --user git+https://github.com/kasiopea-org/pisek` nemusí mít nejnovější verzi, což může vést k problémům. Dobré by bylo na to uživatele nějak upozornit, nebo Písek přímo automaticky aktualizovat.

**Comment by 5K1PY** [comment]
We probably don't want to make random requests to server on startup.
