### ISSUE TITLE
Přepínač `--strict`

### ISSUE THREAD

**Issue by RichardHladik** [kasiopea-org/pisek#74]
(V návaznosti na mo-p-org/vyberko#85)

Momentálně např. varování, že uživatel nemá checker, je jen varování. Bylo by fajn přidat mód, při kterém písek prostě spadne, aby se dal zautomatizovat nějaký finální preflight check před nasazením úloh (ať už do CMS, nebo do Kasiopei).

**Comment by vvolhejn** [comment]
Vyřešeno v 153f00d
