### ISSUE TITLE
Zvýšit limit velikost stacku

### ISSUE THREAD

**Issue by RichardHladik** [kasiopea-org/pisek#77]
jak známo, soutěžní systémy mají směšně velký stack a v řešení se toho často využívá. bylo by fajn něco takového mít i v písku, teď řešení, které má projít, spadne.

mohl by fungovat modul [resource](https://docs.python.org/3.9/library/resource.html). zároveň s tím bychom mohli vyřešit #1

**Comment by 5K1PY** [comment]
Aktuálně používaný ``minibox`` zásobník nelimituje.
