### ISSUE TITLE
Kontrolovat, že hloupá řešení nestíhají časový limit o hodně

### ISSUE THREAD

**Issue by vvolhejn** [kasiopea-org/pisek#8]
Řešení, které nemá stíhat těžší variantu, by ji nemělo stíhat o hodně -- tohle by bylo dobré taky nějak ověřovat. Nicméně to nutně musí zabrat hodně času, takže možná tohle nechceme kontrolovat při základní kontrole ale mít něco jako `pisek --full` co přidá i tyhle časově náročné testy.

**Comment by jiribenes** [comment]
Momentálně vyhodíme timeout error pro řešení, která přesáhnou 100 vteřin i přes to, že to řešení daný subtest stíhat nemá. Tohle by se obecně asi nemělo stávat, protože u takového řešení naopak _chceme_, aby nestihlo vydat odpověď v časovém limitu.

**Comment by 5K1PY** [comment]
Local computers are not super reliable regarding time limits. We can eihter use ``--timeout``, or generate testing_log.json and visualize it. (Which works for CMS as well.)
