### ISSUE TITLE
Umožnit u generátoru specifikovat další soubory, co se mají přeložit

### ISSUE THREAD

**Issue by RichardHladik** [kasiopea-org/pisek#80]
Když je teď generátor shellový skript, co volá pravý generátor víckrát, musí si ho sám přeložit, což je místo pro nekonzistence (blbé flagy, blbá složka atd.). Bylo by fajn moct jako `in_gen` specifikovat víc souborů s tím, že by se spouštěl ten první, ale překládaly všechny.

**Comment by 5K1PY** [comment]
See #145
