### ISSUE TITLE
Statistiky testů

### ISSUE THREAD

**Issue by JiriKalvoda** [kasiopea-org/pisek#87]
Hodilo by se, kdyby se dal zapnout nějaký mód, který by ke každému programu poskytl maximální čas běhu nebo případně i maximální použitou paměť. Občas se hodí vědět, o kolik to nevychází.

**Comment by RichardHladik** [comment]
+1. Paměť asi bude složitější (minimálně protože to je závislé na
platformě), ale měření času by mělo být dost snadné přidělat.

Btw samozřejmě hlavní je, aby to pak běželo dobře v CMSku na serveru.
Ale souhlasím, že mít přibližné odhady časů je při vývoji užitečné.

**Comment by vvolhejn** [comment]
Viz taky #1, #6, #8. Upřímně, ta paměť asi nestojí za to implementovat (typicky moc paměti implikuje moc času), ale ty další určitě dávají smysl. Máš na mysli ještě jiné use casy než #6 a #8?

**Comment by 5K1PY** [comment]
Pro čas ``--timeout``.
Statistiky se dají zobrazit:
```
pisek
pisek extract
pisek visualize
```

**Comment by 5K1PY** [comment]
Paměť viz #112 . Možná ``--memory`` ekvivalent pro ``--timeout``.
