### ISSUE TITLE
Písek ignoruje změnu out_check pro subtask

### ISSUE THREAD

**Issue by JiriKalvoda** [kasiopea-org/pisek#88]
Ahoj!

Když do konfigu napíšu:
```
[test03]
name=Subtask 3
points=3
in_globs=03*.in
out_check=judge
# Název judge (=název souboru bez přípony)
out_judge=src/check
# Potřebuje judge přístup k vstupu?
judge_needs_in=1
# Potřebuje judge přístup k vzorovému výstupu?
judge_needs_out=1
```

Tak se písek tváří naprosto spokojeně, až na to, že danou část konfigu, kde respecifikuji judge pro konkrétní subtask naprosto ignoruje.

**Comment by JiriKalvoda** [comment]
Mám úlohu, co u jednoho subtasku má volnější vyhdnocování než u ostatních. Původní implementace to řešila tak, že judge dostával informaci o subtasku z vnějšku pomocí vzorového výstupu, ale to vážně netuším, jak bych měl zařídit, aby písek generoval "hacknuté" vzorové výstupy, tak tuto informaci dopíše (co CMS bych to uměl dostat vcelku v pohodě, ovšem ne s pískovou mašinerii_

Přišlo mi elegantní tedy mít pro tento subtask judge a jinde používat diff (což např v KSPím opendatovadle je skutečně možné udělat a tak jsem doufal, že by to mohlo jít i tady).

**Comment by RichardHladik** [comment]
Ahoj,

> Mám úlohu, co u jednoho subtasku má volnější vyhdnocování než u
> ostatních. Původní implementace to řešila tak, že judge dostával
> informaci o subtasku z vnějšku pomocí vzorového výstupu, ale to vážně
> netuším, jak bych měl zařídit, aby písek generoval "hacknuté" vzorové
> výstupy, tak tuto informaci dopíše (co CMS bych to uměl dostat vcelku
> v pohodě, ovšem ne s pískovou mašinerii_

Jak bys to byl například schopný udělat v CMS? Přijde mi, že v takovém
případě by to písek měl (ve smyslu "bylo by dobré, aby") umět taky. Mě
teď z hlavy napadá kontrola pomocí názvu souboru, která by měla
fungovat. K názvům souborů má judge v písku přístup stejně jako v CMS.

> Přišlo mi elegantní tedy mít pro tento subtask judge a jinde používat
> diff (což např v KSPím opendatovadle je skutečně možné udělat a tak
> jsem doufal, že by to mohlo jít i tady).

Písek to tak neumí, protože nastavítka ohledně judge jsou globální pro
celou úlohu, a přijde mi, že to i tak dává smysl, vzhledem k tomu, že
zrcadlíme CMS. Vzhledem k tomu, že subtask je jen množina vstupních (a
výstupních) souborů, tak mi nesedí, aby se ten samý vsup měl chovat
jinak, pokud ho vyhodnocuji v jiném subtasku (a i když bys zaručil, že
subtasky s vzájemně jiným nastavením budou mít disjunktní testy, tak je
to prostě divné).

**Comment by JiriKalvoda** [comment]
Díky za rychlou odpověď.

> Jak bys to byl například schopný udělat v CMS?

Nevím, CMS nerozumím natolik, abych byl vůbec schopný posoudit jestli a jak to jde udělat.

Každopádně použití názvů souboru zní použitelně. Trošku jsem se bál, jestli se například uvnitř CMS soubory nemůžou přejmenovávat, ale snad ne.
