### ISSUE TITLE
Neumím vypnout rozlišování subtasků checkrem

### ISSUE THREAD

**Issue by JiriKalvoda** [kasiopea-org/pisek#89]
Ahoj, jak mám písku vysvětlit, že to, že checker nerozliší subtask 3 od 4 prostě není chyba, protože ze vstupu se vážně rozlišit nedají?

V úložce, co přepískovávám se totiž dané subtasky liší jen tím, jak na nich funguje judge.

```
AssertionError: False is not true : Checker 'src/check' není dost přísný: nestěžuje si, když přidáme vstupy ze subtasku 4 do subtasku 3. Subtask 3 má přitom přísnější omezení (tj. je snažší) takže vstupy ze subtasku 4 by neměly být platné pro subtask 3.
````

**Comment by RichardHladik** [comment]
@vvolhejn podíváš se na to? Tuhle funkcionalitu jsi myslím přidával Ty

**Comment by JiriKalvoda** [comment]
Vlastně primární problém vidím v tom, že se mi nikde nepodařilo najít nějakou kompletní dokumentaci (možná protože jsem jenom slepý, v takovém případě poprosím pointer), jak funguje konfig. Jako příklady jsou sice moc faj, ale prostě když člověk potřebuje něco speciálnějšího, tak by se hodil výčet všech nastavítek a jejich možných hodnot včetně detailního vysvětlení funkčnosti.

Pro inspiraci přikládám dokumentaci KSPího opendatovadla. O ní mám totiž pocit, že podobný problém řeší dost hezky.
[config.txt](https://github.com/kasiopea-org/pisek/files/8410683/config.txt)

**Comment by 5K1PY** [comment]
Nyní možné nastavit ``predeccessors``, které detailně popisuje, oproti čemu pouštět checker.
