### ISSUE TITLE
Písek nepouští primární řešení i když se tak tváří

### ISSUE THREAD

**Issue by JiriKalvoda** [kasiopea-org/pisek#90]
Ahoj!

Připadá mi, že písek se chová strašně neintuitivně. Když neprovedu explicitní clean nebo primární řešení nezmodifikuji, tak ho znovu nepouští. 

Ono by to mohlo dávat smysl, ale problém vidím v následujícím:

a) Na rozdíl od informace `  Generátor se nezměnil, používám vstupy vygenerované v předchozím běhu.` toto udělá naprosto bez žádné hlášky. Ba co víc ještě vypíše průběh testování, z čehož bych tak nějak intuitivně usuzoval, že proběhlo. Pokud ne, tak ho tam nemá co psát.
```
Řešení solutions/sol získá 10b ... ··|·······|·····|·······|·······|···············|···············| ok
```

b) Když změním časové limity, tak i tak se neprovede přetestování a tedy můžu snižovat časové limity jak chci a říkat si, že je to v pohodě. Však to přeci ještě projde.

c) Primární a sekundární řešení se z pohledu uživatele chovají dost podobně. V konfigu jsou napsané na stejné řádku a jejich testování vypadá taky naprosto stejně. Nemyslím si, že by tedy měli mít vnitřně tak odlišnou semantimku.

**Comment by vvolhejn** [comment]
Jestli se nemýlím, tohle by neměla být jen záležitost primárního řešení. Písek cachuje všechny vygenerované výstupy a pokud jsou novější, než binárka generátoru, tak je nepřegeneruje. To ale vede k problémům s invalidací cache, jak říkáš. Nejsystematičtější řešení by bylo asi #46.

**Comment by JiriKalvoda** [comment]
Ahoj!

Problém se evidentně netýká jen primárního řešení:
```
jiri@arzen:~/mff/p12x-tasks/zs22/prijimacky/prunik(master)$ pisek clean
Čistím složku: /home/jiri/mff/p12x-tasks/zs22/prijimacky/prunik
jiri@arzen:~/mff/p12x-tasks/zs22/prijimacky/prunik(master)$ pisek
Testuji úlohu /home/jiri/mff/p12x-tasks/zs22/prijimacky/prunik
Upozornění: v configu není specifikovaný checker. Vygenerované vstupy tudíž nejsou zkontrolované. Doporučujeme proto nastavit v sekci [tests] pole `checker`.
runTest (pisek.tests.test_case.SampleExists) ... ok
Generátor src/gen funguje ... ok
Řešení solutions/fast získá 15b ... ·|··|····|······|········| ok
Řešení solutions/skocky_10b získá 10b ... |··|····|······|······T| ok

----------------------------------------------------------------------
Ran 4 tests in 47.006s

OK
jiri@arzen:~/mff/p12x-tasks/zs22/prijimacky/prunik(master)$ pisek --timeout 5
Testuji úlohu /home/jiri/mff/p12x-tasks/zs22/prijimacky/prunik
Upozornění: v configu není specifikovaný checker. Vygenerované vstupy tudíž nejsou zkontrolované. Doporučujeme proto nastavit v sekci [tests] pole `checker`.
runTest (pisek.tests.test_case.SampleExists) ... ok
Generátor src/gen funguje ...
  Generátor se nezměnil, používám vstupy vygenerované v předchozím běhu.
ok
Řešení solutions/fast získá 15b ... ·|··|····|······|········| ok
Řešení solutions/skocky_10b získá 10b ... |··|····|······|········| FAIL

======================================================================
FAIL: Řešení solutions/skocky_10b získá 10b
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jiri/.local/lib/python3.10/site-packages/pisek/tests/test_case.py", line 288, in runTest
    self.assertEqual(
AssertionError: 15 != 10 : Řešení solutions/skocky_10b mělo získat 10b, ale získalo 15b.


----------------------------------------------------------------------
Ran 4 tests in 5.192s

FAILED (failures=1)
[1]i@arzen:~/mff/p12x-tasks/zs22/prijimacky/prunik(master)$ pisek
Testuji úlohu /home/jiri/mff/p12x-tasks/zs22/prijimacky/prunik
Upozornění: v configu není specifikovaný checker. Vygenerované vstupy tudíž nejsou zkontrolované. Doporučujeme proto nastavit v sekci [tests] pole `checker`.
runTest (pisek.tests.test_case.SampleExists) ... ok
Generátor src/gen funguje ...
  Generátor se nezměnil, používám vstupy vygenerované v předchozím běhu.
ok
Řešení solutions/fast získá 15b ... ·|··|····|······|········| ok
Řešení solutions/skocky_10b získá 10b ... |··|····|······|········| FAIL

======================================================================
FAIL: Řešení solutions/skocky_10b získá 10b
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jiri/.local/lib/python3.10/site-packages/pisek/tests/test_case.py", line 288, in runTest
    self.assertEqual(
AssertionError: 15 != 10 : Řešení solutions/skocky_10b mělo získat 10b, ale získalo 15b.


----------------------------------------------------------------------
Ran 4 tests in 0.036s

FAILED (failures=1)
```
Při prvním spuštění 10b řešení spadne na čas.
Při druhém spuštění projde, protože je zvýšený limit.
Při třetím také projde, i když limit je původní. Všimněte si, že třetí spuštění běží jen 0.036s, takže evidentně nic nepouští.

Abych to tedy shrnul. Problém je prostě v tom, že při změně time limitu se neinvaliduje chache.

**Comment by JiriKalvoda** [comment]
Osobně ale problém vidím také/zejména v UI, uživatel na rozdíl od generátoru (`Generátor se nezměnil, používám vstupy vygenerované v předchozím běhu.`) vůbec není informovaný o tom, že se vytahuje něco z cache.  Myslím, že výstup by v takovém případě měl místo `.` vypisovat něco jako `C`, protože je prostě rozdíl, když něco běží a když je jen něco vytaženo z cache.

**Comment by JiriKalvoda** [comment]
Naštěstí funguje workaround:
```
touch solutions/* ; pisek
```

**Comment by JiriKalvoda** [comment]
Mimochodem když už jsme u toho chachování, tak by také dávalo smysl, aby nemusel chcek běžet vždy.

Většinou je totiž psaný v pythonu (na rozdíl od řešení), takže u úloh s dlouhým vstupem i triviální načtení vstupu je v něm prostě pomalejší než spuštění všech řešení.

**Comment by 5K1PY** [comment]
Opraveno ve ``v2``. Nyní všechny použité soubory a proměnné hashujeme, a podle toho se detekuje, zda je zapotřebí znovu pustit daný program.
