### ISSUE TITLE
Kontrola stylu souborů

### ISSUE THREAD

**Issue by JiriKalvoda** [kasiopea-org/pisek#91]
Ahoj!

Bylo by fajn, kdyby písek nějak automaticky kontroloval styl souborů. Například následující věci:
- poslední znak souboru je entr (a to právě jeden)
- soubor neobsahuje divně znaky (mimo ASCI, bílé a netisknutelné znaky…)
- na konci/začátku řádků nejsou mezery
- nikde nejsou dvě mezery po sobě
- …

Dnes jsme narazili na problém, že v samplu nebyl konec posledního řádku a díky tomu řešení jednoho účastníka na něm neprocházelo.

Představuji si to tak, že by se automaticky kontrolovaly všechny vstupy, výstupy (včetně samplů). Případně by se daly jednotlivé funkce v konfigu vypínat.

**Comment by vvolhejn** [comment]
Ahoj, tohle je v podstatě smysl checkeru, ne? Nebo je v tom nějaký rozdíl? Ono je těžké určit, jaká pravidla ještě chceme aplikovat na *všechny* testy bez rozdílu. To se dvěma mezerama by možná mohlo dávat smysl, pokud je něco zadané jako mřížka (ale uznávám - bylo by to divný).

**Comment by JiriKalvoda** [comment]
Tak ale v tom případě je problém, že se nepouští checker na samplech.

Navíc mi připadá, že je špatně, aby každý checker musel implementovat některé základní kontroly. Například aktuální výběrko checker template projde i když poslední řádek není odentrovaný.

Představuji si, že jednotlivé moduly by mohly jít vypínat, takže když by byl vstup mřížka, tak bych do configu napsal něco jako
`check_space=false`. (Navíc tedy používat mezeru v mřížce skoro nikdy nechceš, protože to neskutečně komplikuje parsování, je lepší tam dát `.`).

**Comment by 5K1PY** [comment]
> Last character is newline
> File doesn't contain wierd characters

Solved by IsClean check in `text` format.

> Multiple spaces after each other
> No spaces at the begging and end of line.

Best to write checker for this.
