### ISSUE TITLE
pypy3

### ISSUE THREAD

**Issue by JiriKalvoda** [kasiopea-org/pisek#94]
Ahoj!

Písek mi píše:
```
RuntimeError: gen má neplatný shebang. Pro Python by měl první řádek být '#!/usr/bin/env python3'.  Zkontroluj taky, že soubor používá linuxové konce řádků.
```
Můj program ovšem začíná platným shebangem
```
#!/usr/bin/env pypy3
```
Můj usecase je, že mám generátor v pythonu, ovšem pod CPythonem běží poměrně pomalu, tak jsem chtěl začít používat pypy, ovšem píšek mi hodil klacek pod nohu.

**Comment by JiriKalvoda** [comment]
Řešení:
[0001-Shebang-pythonu-m-e-b-t-i-pypy3-94.patch.txt](https://github.com/kasiopea-org/pisek/files/9482560/0001-Shebang-pythonu-m-e-b-t-i-pypy3-94.patch.txt)
(nemám právo pushnout větev, takže tady to máte jako patch)

**Comment by jiribenes** [comment]
Lehce jsem to do-overengineeroval v PR #96 :)
