### ISSUE TITLE
Odkaz na KSP dokumentaci

### ISSUE THREAD

**Issue by JiriKalvoda** [kasiopea-org/pisek#98]
Ahoj!

Dívám se, že v `pisek/fixtures/soucet_kasiopea/config` je následující odkaz:
```
# Source: $(KSP)/opendata/config for more information
```
Pomineme-li, že se odkazuje na privátní depozitář, tak ten odkaz je naprosto zavádějící, protože KSP a Písek konfig sice na první pohled vypadají podobně, ale při bližším pohledu se liší asi tak ve všem. :D 
Doporučuji změnit na:
```
# Inspired by: $(KSP)/opendata/config
```
A nebo úplně zmínku smazat.

**Comment by vvolhejn** [comment]
Čau, nemám bohužel moc čas Písek maintainovat, tak jsem ti dal přístup k repu (pozvánka je snad [tady](https://github.com/kasiopea-org/pisek/settings/access?guidance_task=)) - problémy, co najdeš, můžeš klidně opravit.

**Comment by jiribenes** [comment]
Jen pro úplnost, ten citovaný config je z Kasiopey [ viz název složky ve které bydlí O:) ], která má s konfiguračním souborem v KSP stejného předka (je to fork zhruba z roku 2015/6).
